---
- name: Add Elastic repo public signing key
  rpm_key: state=present key=https://packages.elastic.co/GPG-KEY-elasticsearch
  tags: 
     - install

- name: Add Logstash repo
  copy: src=logstash.repo dest=/etc/yum.repos.d/ mode=0644
  tags: 
     - install

- name: Install logstash
  yum:
    name: logstash
    update_cache: yes
    state: present
  tags: 
     - install

