---
- include: timezone.yaml
- include: iptables.yaml
- include: java7.yaml
- include: irods-config.yaml
- include: condor.yaml
- include: docker.yaml
- include: postgres.yaml
- include: db-creator.yaml
