
#
# Properties file configuration
#
- name: ensure data directory exists
  file: path=/etc/cas state=directory owner={{tomcat_user}} group={{tomcat_user}}
  tags:
    - cas
    - properties

- name: copy all template configs
  template: src=config/cas.properties dest=/etc/cas/cas.properties
  tags:
    - cas
    - properties

- name: add proxy for maven
  template: src=maven/settings.xml dest=/home/{{ansible_ssh_user}}/.m2/settings.xml
  tags:
    - cas
    - properties

- name: copy log4j.xml
  template: src=log4j.xml.j2 dest=/etc/cas/log4j2.xml
  tags:
    - cas
    - properties

- name: set data ownership [all data is owned by tomcat]
  file: path=/etc/cas owner={{tomcat_user}} group={{tomcat_user}} recurse=true
  tags:
    - cas
    - properties

- name: ensure ssl certificate directory exists (if required)
  file: path={{ ssl_certificate_server_dir }} state=directory owner={{tomcat_user}} group={{tomcat_user}}
  when: cas.do_ssl_config
  tags:
    - cas
    - properties
    - apache_vhost

- name: copy SSL public key
  copy: src={{ cas_ssl_cert_file }} dest={{ssl_certificate_server_dir}}/{{cas_ssl_cert_file}}
  when: cas.do_ssl_config
  tags:
    - cas
    - properties
    - apache_vhost

- name: copy SSL private key
  copy: src={{ cas_ssl_key_file }} dest={{ssl_certificate_server_dir}}/{{cas_ssl_key_file}}
  when: cas.do_ssl_config
  tags:
        - cas
        - properties
        - apache_vhost

- name: set data ownership [all data is owned by tomcat]
  file: path={{ssl_certificate_server_dir}} owner={{tomcat_user}} group={{tomcat_user}} recurse=true
  when: cas.do_ssl_config
  tags:
    - cas
    - properties

#
# WAR file deployment and virtual host configuration
#


- name: cas | download overlay
  git: repo={{cas.git_url}}
       dest=/home/{{ ansible_ssh_user }}/casbuild/{{cas.git_project_name}}


- name: cas | build cas overlay
  shell:
       cd /home/{{ansible_ssh_user}}/casbuild/{{cas.git_project_name}}; mvn clean; mvn package;
       cp target/{{cas.git_project_name}}.war target/cas.war;
       cp target/cas.war /usr/share/tomcat/webapps/cas.war

